# Generated by Django 5.2.8 on 2025-11-19 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('email_verified', models.BooleanField(default=False)),
                ('last_otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=10)),
                ('otp_purpose', models.CharField(blank=True, choices=[('registration', 'Registration'), ('password_reset', 'Password Reset')], max_length=32)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_consumed_at', models.DateTimeField(blank=True, null=True)),
                ('otp_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
