# Generated by Django 5.2.8 on 2025-11-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_bookmark'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookmark',
            new_name='feed_bookma_user_id_6e10dc_idx',
            old_name='feed_bookma_user_id__3b9553_idx',
        ),
    ]
